---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-podlodka-php
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-podlodka-php
  template:
    metadata:
      labels:
        app: hello-podlodka-php
    spec:
      containers:
        - name: nginx
          image: hello-podlodka-nginx:0.0.1
          imagePullPolicy: Never
          env:
            - name: PHP_FPM_HOST
              value: 127.0.0.1
          ports:
            - containerPort: 80
        - name: php-fpm
          image: hello-podlodka-php-fpm:0.0.2
          imagePullPolicy: Never
          env:
            - name: SESSION_DRIVER
              value: file

---
apiVersion: v1
kind: Service
metadata:
  name: hello-podlodka-php-service
spec:
  selector:
    app: hello-podlodka-php
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-podlodka
spec:
  rules:
    - host: hello-podlodka.lcl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-podlodka-php-service
                port:
                  number: 80
